import { p, steps, note, walk, type HelpArticle } from "@/lib/help/types";

/**
 * Every Help article DropQ ships.
 *
 * ⚠️ RULE: nothing here describes behaviour that has not been read in the code.
 * `verifiedAgainst` on each article names where. Several answers below are
 * deliberately blunter than a marketing site would be — "starting Stripe is not
 * finishing it", "relaunch spends another drop" — because those are exactly the
 * places vendors have been surprised.
 *
 * Written 2026-08-29 against the repo at that date.
 */
export const HELP_ARTICLES: HelpArticle[] = [
  /* ------------------------- Getting started -------------------------- */
  {
    id: "what-is-dropq",
    slug: "what-is-dropq",
    title: "What DropQ is",
    question: "What is DropQ?",
    summary: "DropQ turns what you make into a drop — one link and a QR code customers order from.",
    category: "getting-started",
    keywords: ["dropq", "what is", "overview", "start", "basics"],
    body: [
      p("DropQ is a way to sell what you make without building a shop. You create a drop, share one link, and customers order from it. Money goes to your own Stripe account; orders arrive in your dashboard."),
      p("There is no storefront to design and nothing to install. Every drop gets its own public page, its own link and its own QR code."),
    ],
    related: ["what-is-a-drop", "what-you-need-to-start", "create-your-first-drop"],
    routes: ["/dashboard"],
    priority: 1,
    verifiedAgainst: "app/dashboard/page.tsx, app/s/[slug]/[dropId]/page.tsx",
  },
  {
    id: "what-is-a-drop",
    slug: "what-is-a-drop",
    title: "What a drop is",
    question: "What is a drop?",
    summary: "A drop is what you're selling, when customers can order it, and where they collect it.",
    category: "getting-started",
    keywords: ["drop", "definition", "what is a drop", "menu"],
    body: [
      p("A drop is one selling event. It holds the items you're offering, the window when customers can order, and the pickup details."),
      p("Each drop is separate. Its items, quantities and dates belong to it alone, and it gets its own link and QR code."),
    ],
    related: ["drop-types", "how-drop-dates-work", "create-your-first-drop"],
    routes: ["/dashboard/drops"],
    priority: 2,
    verifiedAgainst: "prisma/schema.prisma model Drop",
  },
  {
    id: "what-you-need-to-start",
    slug: "what-you-need-to-start",
    title: "What you need before selling",
    question: "What do I need before I can start selling?",
    summary: "An email address, a Stripe account, and something to sell. Nothing else is required.",
    category: "getting-started",
    keywords: ["requirements", "before", "start selling", "need", "setup"],
    body: [
      p("Three things: your DropQ account, a connected Stripe account, and at least one item in a drop."),
      p("Nothing about your store profile is required. Tagline, bio, logo, location and colours are all optional — you can fill them in whenever you like, or never."),
      note("Verifying your email is worth doing for account security, but it does not gate selling. You can publish and take orders with an unverified address."),
    ],
    related: ["connect-stripe", "create-your-first-drop", "verify-your-email"],
    priority: 3,
    verifiedAgainst: "lib/actions/dashboard.ts updateStoreAction, lib/activation.ts",
  },
  {
    id: "do-i-need-stripe",
    slug: "do-i-need-stripe",
    title: "Whether you need Stripe",
    question: "Do I need Stripe?",
    summary: "Yes. A drop can't go live until Stripe can take card payments for you.",
    category: "getting-started",
    keywords: ["stripe", "required", "need", "payment", "publish"],
    body: [
      p("Yes. DropQ takes card payments through Stripe, and a drop can only be published once your Stripe account can actually accept charges."),
      p("You can do everything else first — build drops, add items, set dates — and save them as drafts. Nothing is lost while Stripe is pending."),
    ],
    related: ["connect-stripe", "stripe-started-vs-ready", "why-cant-i-publish"],
    routes: ["/dashboard/payments"],
    priority: 4,
    verifiedAgainst: "lib/payments.ts resolveDropStatus, isVendorSellable",
  },
  {
    id: "first-week",
    slug: "first-week",
    title: "Your first week",
    question: "What should I do first?",
    summary: "Connect Stripe, build one drop, publish it, share the link. Everything else can wait.",
    category: "getting-started",
    keywords: ["first", "start", "checklist", "order", "steps"],
    body: [
      p("Five things, in this order: connect Stripe, build one drop, set your dates, publish, share it. Everything else can wait."),
      walk(
        {
          title: "Start on your dashboard",
          text: "The checklist ticks itself off from what you've actually done — you never mark anything complete by hand.",
          shot: "getting-started-dashboard",
        },
        {
          title: "Everything starts with a drop",
          text: "A drop is one sale with a start and an end. New drop is on the Drops page.",
          shot: "getting-started-new-drop",
        },
        {
          title: "Help is always in the header",
          text: "It knows which page you're on and shows the articles for it first.",
          shot: "getting-started-help",
        },
      ),
      note("Connecting Stripe is the only hard requirement. Until it can take card payments, DropQ saves your drops as drafts."),
    ],
    related: ["connect-stripe", "create-your-first-drop", "share-your-drop"],
    routes: ["/dashboard"],
    priority: 5,
    verifiedAgainst: "lib/activation.ts activationState",
  },

  /* ----------------------------- Drops -------------------------------- */
  {
    id: "drop-types",
    slug: "drop-types",
    title: "Regular drops vs live selling drops",
    question: "What's the difference between a regular drop and a live selling drop?",
    summary: "A regular drop takes orders ahead of time. A live selling drop is for selling in person, right now.",
    category: "drops",
    keywords: ["regular", "live selling", "preorder", "mode", "type", "difference"],
    body: [
      p("A regular drop takes orders ahead of time. You set a window when customers can order, and a later window when they collect. Ordering locks itself at the close time."),
      p("A live selling drop is for selling in person. It opens immediately, has no order window, and stays open until you close it — customers scan your QR and order while they're standing with you."),
      note("You choose this once. The type cannot be changed after a drop is created; correcting it means deleting the drop and starting again, which on the Free plan spends another of your lifetime drops."),
    ],
    related: ["how-drop-dates-work", "create-your-first-drop", "starter-drop-limit"],
    routes: ["/dashboard/drops", "/dashboard/drops/new"],
    priority: 1,
    verifiedAgainst: "components/drop-editor.tsx, lib/drop-status.ts, lib/actions/dashboard.ts updateDropFullAction",
  },
  {
    id: "create-your-first-drop",
    slug: "create-your-first-drop",
    title: "Creating your first drop",
    question: "How do I create my first drop?",
    summary: "Pick the drop type, add details and dates, add your items, then save or publish.",
    category: "drops",
    keywords: ["create", "new drop", "first drop", "make", "build"],
    body: [
      walk(
        {
          title: "Choose the drop type",
          text: "Regular drop for a scheduled sale, Live selling for one you open and close by hand. You pick this once — it can't be changed later.",
          shot: "create-drop-choose-type",
        },
        {
          title: "Title and description",
          text: "This is what customers read on your storefront. Say what it is and anything they need to know before ordering.",
          shot: "create-drop-details",
        },
        {
          title: "Fulfilment and location",
          text: "Pickup, local delivery, or on-site handoff — and where it happens.",
          shot: "create-drop-fulfilment",
        },
        {
          title: "Add your items, then save",
          text: "Each item needs a name, a price and a quantity for this drop. Save as a draft, or publish if Stripe is connected.",
          shot: "create-drop-save",
        },
      ),
      p("You can edit everything afterwards, including while the drop is live. Dates come next — see How drop dates work."),
    ],
    related: ["drop-types", "how-drop-dates-work", "add-items", "publish-a-drop"],
    routes: ["/dashboard/drops/new", "/dashboard/drops"],
    priority: 2,
    verifiedAgainst: "components/drop-editor.tsx, lib/actions/dashboard.ts createDropAction",
  },
  {
    id: "how-drop-dates-work",
    slug: "how-drop-dates-work",
    title: "How drop dates work",
    question: "How do drop dates work?",
    summary: "Two windows in sequence: when customers can order, then when they collect.",
    category: "drops",
    keywords: ["dates", "order window", "pickup window", "schedule", "opens", "closes", "time"],
    body: [
      p("A regular drop has two windows, and they run in order."),
      walk(
        {
          title: "When customers can order",
          text: "From when, until when. Ordering locks itself at the close time — you don't have to be there.",
          shot: "dates-order-window",
        },
        {
          title: "When they collect",
          text: "Starts at or after ordering closes, so you have time to make everything.",
          shot: "dates-pickup-window",
        },
        {
          title: "How it reads once it's set",
          text: "Both windows, in your store's timezone.",
          shot: "dates-summary",
        },
      ),
      p("DropQ enforces the relationship: ordering must close before or exactly when pickup starts, each window needs both a start and an end, and an end must come after its start."),
      note("Times are shown in your store's timezone, which you can set in Store settings. Live selling drops have no windows — they're open while you keep them open."),
    ],
    related: ["drop-types", "close-a-drop", "why-isnt-my-drop-visible"],
    routes: ["/dashboard/drops/new"],
    priority: 3,
    verifiedAgainst: "lib/drop-schedule.ts validateDropSchedule, lib/drop-status.ts computeDropPhase",
  },
  {
    id: "edit-a-drop",
    slug: "edit-a-drop",
    title: "Changing a drop",
    question: "How do I change a drop after creating it?",
    summary: "Open the drop and choose Edit. Changes apply to that drop; no copy is made.",
    category: "drops",
    keywords: ["edit", "change", "update", "modify"],
    body: [
      p("Open the drop and choose Edit drop. You can change the title, description, dates, pickup details and items — including while the drop is live."),
      p("If you change pickup details on a drop that already has orders, DropQ tells those customers."),
      note("The one thing you cannot change is the drop type. Regular and live selling are fixed when the drop is created."),
    ],
    related: ["remove-an-item", "drop-types", "change-inventory"],
    routes: ["/dashboard/drops"],
    priority: 4,
    verifiedAgainst: "lib/actions/dashboard.ts updateDropFullAction, notifyPickupChanged",
  },
  {
    id: "relaunch-a-drop",
    slug: "relaunch-a-drop",
    title: "Relaunching a previous drop",
    question: "Can I duplicate a previous drop?",
    summary: "Relaunch copies a drop's items and pickup details into a brand new draft.",
    category: "drops",
    keywords: ["relaunch", "duplicate", "copy", "repeat", "again"],
    body: [
      p("Relaunch takes an existing drop and copies its items and pickup details into a new draft. You set fresh dates and publish when you're ready. The original is untouched."),
      note("Relaunch creates a NEW drop, so on the Free plan it counts as another of your three lifetime drops."),
    ],
    related: ["starter-drop-limit", "create-your-first-drop"],
    routes: ["/dashboard/drops"],
    priority: 5,
    verifiedAgainst: "lib/actions/dashboard.ts duplicateDropAction",
  },
  {
    id: "close-a-drop",
    slug: "close-a-drop",
    title: "Closing and reopening a drop",
    question: "How do I close a drop, and can I reopen it?",
    summary: "Closing stops new orders and keeps everything. You can reopen it if Stripe is still ready.",
    category: "drops",
    keywords: ["close", "closing", "reopen", "stop", "end", "finish"],
    body: [
      p("Closing a drop stops new orders. Your existing orders, items, sales history and customers are all kept, and you can reopen the drop later."),
      p("A regular drop also closes itself once its order window ends — you don't have to be there."),
      note("Deleting is different. Deleting a drop removes it and its orders permanently, and it does not give back a Free-plan drop slot."),
    ],
    related: ["how-drop-dates-work", "starter-drop-limit", "remove-an-item"],
    routes: ["/dashboard/drops"],
    priority: 6,
    verifiedAgainst: "lib/actions/dashboard.ts updateDropStatusAction, lib/drop-close.ts closeExpiredDrops",
  },
  {
    id: "publish-a-drop",
    slug: "publish-a-drop",
    title: "Publishing a drop",
    question: "What happens when I publish?",
    summary: "Publishing puts the drop on your storefront, orderable during the window you set.",
    category: "drops",
    keywords: ["publish", "live", "go live", "publishing"],
    body: [
      walk(
        {
          title: "Publish it",
          text: "Publishing puts the drop on your storefront. Customers can order during the window you set — not before it opens, not after it closes.",
          shot: "publish-button",
        },
        {
          title: "It goes live and counts down",
          text: "The drop shows its status and the time left until ordering closes.",
          shot: "publish-live-state",
        },
        {
          title: "Copy the link",
          text: "Publishing does not tell anyone. This link is what brings customers to the drop — post it wherever they already follow you.",
          shot: "publish-share-link",
        },
        {
          title: "Or use the QR code",
          text: "Every drop has its own QR code. Print it and put it on the table, on the box, or in the window.",
          shot: "publish-qr",
        },
      ),
      note("A drop can only be published when Stripe can take card payments for you. If it can't, DropQ saves your work as a draft instead of putting a checkout in front of customers that cannot take their money."),
    ],
    related: ["share-your-drop", "why-cant-i-publish", "connect-stripe"],
    routes: ["/dashboard/drops"],
    priority: 7,
    verifiedAgainst: "lib/payments.ts resolveDropStatus, lib/activation.ts publishGate",
  },

  /* ---------------------------- Products ------------------------------ */
  {
    id: "add-items",
    slug: "add-items",
    title: "Adding items to a drop",
    question: "How do I add products?",
    summary: "Add them in the drop editor with a name, price and quantity — or pull them from your saved products.",
    category: "products",
    keywords: ["items", "products", "add", "menu", "photos"],
    body: [
      walk(
        {
          title: "Name and price",
          text: "The minimum an item needs. You can also add up to six photos and a short description.",
          shot: "add-items-row",
        },
        {
          title: "Quantity for this drop",
          text: "How many you're selling in THIS drop, not how many you own. When it hits zero the item sells out and the rest of the drop stays open.",
          shot: "add-items-inventory",
        },
        {
          title: "Watch it sell through",
          text: "Once the drop is running, each item shows sold against the quantity you set.",
          shot: "add-items-result",
        },
      ),
      p("If you've saved products before, use Add from saved products to pull in the name, price and photos. You still set the quantity for each drop."),
      note("New items you type into a drop are saved to your product library automatically, so you can reuse them. There's a checkbox to opt out."),
    ],
    related: ["product-library", "how-inventory-works", "remove-an-item"],
    routes: ["/dashboard/drops/new", "/dashboard/products"],
    priority: 1,
    verifiedAgainst: "components/drop-editor.tsx, lib/actions/dashboard.ts saveProductsToLibrary",
  },
  {
    id: "product-library",
    slug: "product-library",
    title: "Your product library",
    question: "What is the product library?",
    summary: "Reusable products you can drop into any future drop. It holds no stock count.",
    category: "products",
    keywords: ["library", "saved products", "reuse", "catalogue", "catalog"],
    body: [
      p("The product library holds the things you sell often — name, price, description and photos — so you don't retype them for every drop."),
      p("It does not hold quantities. How many you're selling is set per drop, because it changes every time."),
      note("Editing a library product does not change drops that already exist. A drop keeps its own copy of the price and details from when you added it."),
    ],
    related: ["add-items", "how-inventory-works"],
    routes: ["/dashboard/products"],
    priority: 2,
    verifiedAgainst: "prisma/schema.prisma VendorProduct + Product, components/product-library.tsx",
  },
  {
    id: "how-inventory-works",
    slug: "how-inventory-works",
    title: "How inventory works",
    question: "How does inventory work?",
    summary: "It's the quantity available in one drop, and DropQ won't let you be oversold.",
    category: "products",
    keywords: ["inventory", "stock", "quantity", "how many", "sold out", "oversell"],
    body: [
      p("Each item in a drop has a quantity for that drop. As orders come in, DropQ counts them against it and shows how much is left."),
      p("You cannot be oversold. The check happens on the server as part of the order, so two customers buying the last one at the same moment can't both succeed."),
    ],
    related: ["change-inventory", "sold-out", "add-items"],
    routes: ["/dashboard/drops/new"],
    priority: 3,
    verifiedAgainst: "lib/actions/order.ts placeOrderAction (conditional UPDATE on sold + qty <= inventory)",
  },
  {
    id: "change-inventory",
    slug: "change-inventory",
    title: "Changing inventory after publishing",
    question: "Can I change inventory after publishing?",
    summary: "Yes. Edit the drop and change the quantity; orders already placed are unaffected.",
    category: "products",
    keywords: ["change inventory", "more stock", "add stock", "adjust", "quantity"],
    body: [
      p("Yes. Edit the drop and change the quantity on any item. Raising it opens up more to sell; lowering it stops sales sooner."),
      p("Orders already placed are never affected — the number you set is the total available for the drop, and what's already sold counts against it."),
    ],
    related: ["how-inventory-works", "sold-out", "edit-a-drop"],
    priority: 4,
    verifiedAgainst: "lib/actions/dashboard.ts updateDropFullAction",
  },
  {
    id: "sold-out",
    slug: "sold-out",
    title: "When something sells out",
    question: "What happens when something sells out?",
    summary: "It shows as sold out and can't be added to a cart. The rest of the drop keeps selling.",
    category: "products",
    keywords: ["sold out", "out of stock", "sells out", "empty"],
    body: [
      p("When an item reaches its quantity it shows as Sold out on your drop page and can't be added to a cart. Customers with the page already open see it flip without refreshing."),
      p("Everything else in the drop keeps selling normally."),
    ],
    related: ["how-inventory-works", "change-inventory"],
    priority: 5,
    verifiedAgainst: "components/storefront-order.tsx, app/api/drops/[id]/inventory/route.ts",
  },
  {
    id: "remove-an-item",
    slug: "remove-an-item",
    title: "Removing an item from a drop",
    question: "What happens if I remove an item customers already bought?",
    summary: "It stops being sellable and shows as sold out. The orders and your sales history are kept.",
    category: "products",
    keywords: ["remove", "delete item", "take off", "retire"],
    body: [
      p("Removing an item nobody has bought deletes it."),
      p("Removing an item that already has orders does not delete it. DropQ retires it instead: no more can be bought, it shows as sold out on your drop page, and those orders — plus your per-item sales figures — stay intact."),
      note("DropQ asks you to confirm before removing an item that has orders."),
    ],
    related: ["how-inventory-works", "edit-a-drop"],
    priority: 6,
    verifiedAgainst: "lib/drop-items.ts planRemovals, lib/actions/dashboard.ts updateDropFullAction",
  },

  /* ---------------------------- Payments ------------------------------ */
  {
    id: "connect-stripe",
    slug: "connect-stripe",
    title: "Connecting Stripe",
    question: "How do I connect Stripe?",
    summary: "From Payments, choose Connect with Stripe and finish Stripe's own setup.",
    category: "payments",
    keywords: ["stripe", "connect", "setup", "payments", "bank", "payout"],
    body: [
      walk(
        {
          title: "Go to Payments",
          text: "Connect with Stripe is the only thing on the page until you've done it.",
          shot: "stripe-payments-page",
        },
        {
          title: "DropQ hands you to Stripe",
          text: "The rest happens on Stripe's own site. Stripe asks for your business details, an ID check, and the bank account you want money paid into — DropQ never sees or stores any of it.",
          shot: "stripe-handoff",
        },
        {
          title: "Come back and check the status",
          text: "Coming back from Stripe is not the same as being finished. Payments tells you when Stripe can actually take charges — that's when you can publish.",
          shot: "stripe-connected",
        },
      ),
      note("Coming back from Stripe is not the same as being finished. See the next article."),
    ],
    related: ["stripe-started-vs-ready", "when-do-i-get-paid", "why-cant-i-publish"],
    routes: ["/dashboard/payments"],
    priority: 1,
    verifiedAgainst: "lib/actions/stripe.ts connectStripeAction, app/dashboard/payments/page.tsx",
  },
  {
    id: "stripe-started-vs-ready",
    slug: "stripe-started-vs-ready",
    title: "Started vs ready to take payments",
    question: "Why does DropQ say my Stripe setup isn't complete?",
    summary: "Creating a Stripe account isn't the same as being able to take charges — Stripe decides when.",
    category: "payments",
    keywords: ["incomplete", "setup incomplete", "pending", "review", "not complete", "stripe"],
    body: [
      p("DropQ creates your Stripe account the moment you begin, so from then on your account exists. That is not the same as being able to take money."),
      p("Only when Stripe confirms your account can accept charges does DropQ let you publish. Stripe may still be reviewing your details, or may need something more from you."),
      steps(
        "On the Payments page, choose Continue setup to go back to Stripe and finish anything outstanding.",
        "Choose Refresh status to have DropQ re-check with Stripe.",
      ),
      note("If Stripe is reviewing you, it can take a few minutes. Nothing is lost meanwhile — build your drops as drafts."),
    ],
    related: ["connect-stripe", "why-cant-i-publish", "stripe-stopped-working"],
    routes: ["/dashboard/payments"],
    priority: 2,
    verifiedAgainst: "lib/activation.ts stripeActivationState, app/dashboard/payments/page.tsx",
  },
  {
    id: "when-do-i-get-paid",
    slug: "when-do-i-get-paid",
    title: "When you get paid",
    question: "When do I get paid?",
    summary: "Customers pay into your own Stripe account, and Stripe pays out on its schedule.",
    category: "payments",
    keywords: ["paid", "payout", "money", "when", "bank", "settlement"],
    body: [
      p("Payments go to your own Stripe account, not to DropQ. Stripe then pays out to your bank on the schedule set on your Stripe account."),
      p("DropQ does not hold your money and does not control when you're paid. Payout timing, balances and bank details all live in your Stripe dashboard, which you can open from the Payments page."),
    ],
    related: ["what-dropq-charges", "connect-stripe"],
    routes: ["/dashboard/payments"],
    priority: 3,
    verifiedAgainst: "lib/checkout-session.ts (direct charge on the connected account)",
  },
  {
    id: "what-dropq-charges",
    slug: "what-dropq-charges",
    title: "What DropQ charges",
    question: "What fees does DropQ charge?",
    summary: "A small percentage of each order, on top of Stripe's own processing fee.",
    category: "payments",
    keywords: ["fee", "fees", "cost", "charge", "percent", "commission", "price"],
    body: [
      p("DropQ takes a percentage of each order as a platform fee. It's shown on your Payments page, along with what you've paid to date."),
      p("Stripe charges its own processing fee separately. Because the payment is made on your Stripe account, you are the merchant of record and Stripe's fee comes out of your proceeds — DropQ's fee is on top of that."),
      note("You can choose whether to absorb DropQ's fee or pass it to customers as a visible service fee. That setting is in Store settings."),
    ],
    related: ["when-do-i-get-paid", "plans-and-limits", "pass-the-fee"],
    routes: ["/dashboard/payments", "/dashboard/billing"],
    priority: 4,
    verifiedAgainst: "lib/stripe.ts feePercent/calcFeeCents, lib/checkout-session.ts application_fee_amount",
  },
  {
    id: "pass-the-fee",
    slug: "pass-the-fee",
    title: "Absorbing or passing on the fee",
    question: "Can I make customers pay the DropQ fee?",
    summary: "Yes. In Store settings you choose whether the fee comes out of your takings or is added at checkout.",
    category: "payments",
    keywords: ["absorb", "pass", "service fee", "customer pays", "fee mode"],
    body: [
      p("In Store settings you can choose either option. Absorb (the default) takes DropQ's fee out of your proceeds and customers never see it. Pass it on adds it as a visible Service fee line at checkout."),
      p("This does not affect Stripe's own processing fee, which always comes out of your proceeds."),
    ],
    related: ["what-dropq-charges", "when-do-i-get-paid"],
    routes: ["/dashboard/store"],
    priority: 5,
    verifiedAgainst: "lib/actions/dashboard.ts feeMode, lib/checkout-session.ts passFee",
  },
  {
    id: "stripe-stopped-working",
    slug: "stripe-stopped-working",
    title: "If Stripe pauses your account",
    question: "What happens if Stripe stops accepting payments for me?",
    summary: "Your storefront stops taking orders. Your drops, orders and customers are safe.",
    category: "payments",
    keywords: ["restricted", "paused", "disabled", "stripe problem", "stopped", "suspended"],
    body: [
      p("If Stripe turns off card payments for your account, DropQ stops publishing new drops and your storefront stops taking orders. Stripe usually does this when it needs more information from you."),
      p("Nothing is lost. Your drops, items, orders and customers are all safe, you can still edit drafts, and you can still close a live drop."),
      p("Your dashboard shows a Selling is paused message with a link into Stripe to fix it. Once Stripe is happy, publishing works again."),
    ],
    related: ["stripe-started-vs-ready", "why-cant-i-publish"],
    routes: ["/dashboard/payments", "/dashboard"],
    priority: 6,
    verifiedAgainst: "lib/activation.ts stripeActivationState 'restricted', components/vendor-activation-card.tsx",
  },

  /* ----------------------------- Orders ------------------------------- */
  {
    id: "where-are-my-orders",
    slug: "where-are-my-orders",
    title: "Where your orders appear",
    question: "Where do I see orders?",
    summary: "Under Orders — every order from every drop, newest first.",
    category: "orders",
    keywords: ["orders", "where", "see", "list", "find"],
    body: [
      p("Orders shows every order across all your drops, newest first, and you can filter by status. Each drop's own page also lists just that drop's orders."),
      p("Your dashboard tells you how many still need preparing."),
    ],
    related: ["order-statuses", "is-an-order-paid"],
    routes: ["/dashboard/orders", "/dashboard"],
    priority: 1,
    verifiedAgainst: "app/dashboard/orders/page.tsx, app/dashboard/drops/[id]/page.tsx",
  },
  {
    id: "order-statuses",
    slug: "order-statuses",
    title: "Order statuses",
    question: "What do the order statuses mean?",
    summary: "New, in progress, ready, completed, canceled — you move each order along as you work.",
    category: "orders",
    keywords: ["status", "new", "ready", "in progress", "completed", "cancel", "fulfil"],
    body: [
      p("A paid order arrives as New. You move it along as you work: In progress while you're making it, Ready when it's waiting for the customer, Completed once handed over. Canceled is there if it falls through."),
      p("You change a status straight from the order list — no need to open anything."),
    ],
    related: ["where-are-my-orders", "pickup-and-fulfilment"],
    routes: ["/dashboard/orders"],
    priority: 2,
    verifiedAgainst: "app/dashboard/orders/page.tsx FILTERS, lib/orders.ts orderStatusLabel",
  },
  {
    id: "is-an-order-paid",
    slug: "is-an-order-paid",
    title: "Knowing an order is paid",
    question: "How do I know an order has been paid?",
    summary: "Orders only appear once payment is confirmed, and each shows a payment badge.",
    category: "orders",
    keywords: ["paid", "payment", "confirmed", "pending", "money"],
    body: [
      p("An order is created when a customer checks out but is only marked paid once Stripe confirms the payment. Unpaid, abandoned checkouts don't appear in your order list."),
      p("Each order shows a payment badge alongside its status, so you can tell at a glance."),
    ],
    related: ["order-statuses", "when-do-i-get-paid"],
    routes: ["/dashboard/orders"],
    priority: 3,
    verifiedAgainst: "lib/checkout.ts finalizePaidOrder, lib/orders.ts paymentLabel",
  },
  {
    id: "pickup-and-fulfilment",
    slug: "pickup-and-fulfilment",
    title: "Handling pickup",
    question: "How do I handle pickup and fulfilment?",
    summary: "Customers see your pickup window and location on their order; you can tell them when you've arrived.",
    category: "orders",
    keywords: ["pickup", "collect", "fulfil", "handover", "arrived", "delivery"],
    body: [
      p("Customers see the pickup window, location and any notes you set on the drop. Adding a How to find you line helps them spot you at a market."),
      p("When you're at the pickup spot, the drop page has an I'm at the pickup location button that tells everyone with an order that you've arrived."),
      p("Mark each order Ready when it's waiting, and Completed when it's handed over."),
    ],
    related: ["order-statuses", "how-drop-dates-work"],
    routes: ["/dashboard/drops"],
    priority: 4,
    verifiedAgainst: "lib/actions/dashboard.ts vendorArrivedAction, lib/pickup.ts",
  },
  {
    id: "message-a-customer",
    slug: "message-a-customer",
    title: "Messaging someone about their order",
    question: "Can I message a customer?",
    summary: "Yes — every order and customer has a Message button that opens a private conversation.",
    category: "orders",
    keywords: ["message", "contact", "chat", "reply", "customer"],
    body: [
      p("Every order and every customer has a Message button. It opens a private conversation between you and that person, and their replies come back to your Messages inbox."),
      p("If a customer gave a phone number, the order also offers call and text links."),
    ],
    related: ["announcements", "customer-list"],
    routes: ["/dashboard/orders", "/dashboard/messages", "/dashboard/customers"],
    priority: 5,
    verifiedAgainst: "lib/messaging.ts sendMessage, components/message-customer-button.tsx",
  },

  /* ------------------------ QR codes & sharing ------------------------ */
  {
    id: "share-your-drop",
    slug: "share-your-drop",
    title: "Sharing a drop",
    question: "How do I share my drop?",
    summary: "Every drop has a public link and its own QR code, both on the drop's page.",
    category: "sharing",
    keywords: ["share", "link", "url", "send", "post", "promote"],
    body: [
      p("Open the drop and you'll find its public link with a Copy link button, and its QR code with a download button."),
      p("Post the link wherever your customers are; print the QR for your table, your packaging or a poster. Both go to the same place."),
      note("Publishing alone doesn't tell anyone. Sharing is what brings customers to a drop."),
    ],
    related: ["drop-qr-code", "where-to-put-qr", "publish-a-drop"],
    routes: ["/dashboard/drops"],
    priority: 1,
    verifiedAgainst: "app/dashboard/drops/[id]/page.tsx shareUrl + QRCode.toDataURL",
  },
  {
    id: "drop-qr-code",
    slug: "drop-qr-code",
    title: "Your drop's QR code",
    question: "What is my drop QR code?",
    summary: "A QR code that opens that one drop. Each drop has its own; there is no store-wide code.",
    category: "sharing",
    keywords: ["qr", "qr code", "scan", "code", "print"],
    body: [
      p("Every drop gets its own QR code, which opens that drop's public page. Anyone who scans it can order, as long as ordering is open."),
      p("There is no single store-wide or account-wide DropQ QR code. If you run a new drop, share that drop's own code."),
      note("The QR downloads as an image you can print at any size. Test it with your own phone before printing a lot of them."),
    ],
    related: ["where-to-put-qr", "share-your-drop", "qr-not-working"],
    routes: ["/dashboard/drops"],
    priority: 2,
    verifiedAgainst: "app/dashboard/drops/[id]/page.tsx (QR is per drop; no store-level QR exists in the codebase)",
  },
  {
    id: "where-to-put-qr",
    slug: "where-to-put-qr",
    title: "Where to put your QR code",
    question: "Where should I put my QR code?",
    summary: "Anywhere a customer is standing with a phone — your table, packaging, or a window.",
    category: "sharing",
    keywords: ["qr", "print", "poster", "table", "market", "sign", "packaging"],
    body: [
      p("Anywhere someone might want to order and has a phone in their hand: a card on your market table, a sticker on your packaging so people can reorder, a sign in a window, or the back of a flyer."),
      p("Give it a line of context — people scan a code far more readily when they know what it does."),
    ],
    related: ["drop-qr-code", "share-your-drop"],
    priority: 3,
    verifiedAgainst: "app/dashboard/drops/[id]/page.tsx",
  },
  {
    id: "qr-not-working",
    slug: "qr-not-working",
    title: "If your QR code isn't working",
    question: "Why isn't my QR code working?",
    summary: "It usually still scans fine — the drop behind it just isn't taking orders right now.",
    category: "sharing",
    keywords: ["qr not working", "scan", "broken", "doesn't work", "error"],
    body: [
      p("A downloaded QR code doesn't stop working. When a scan doesn't lead to an order, it's almost always the drop behind it:"),
      steps(
        "The drop is still a draft, so it isn't public yet.",
        "The order window hasn't opened, or has already closed.",
        "The drop has been closed.",
        "Everything in it is sold out.",
      ),
      p("Open the drop in your dashboard — it will say which of these applies. If you printed a QR for an older drop, that code still points at the old drop, not your latest one."),
    ],
    related: ["drop-qr-code", "why-isnt-my-drop-visible", "why-cant-customers-order"],
    priority: 4,
    verifiedAgainst: "lib/drop-status.ts isOrderingOpen, app/s/[slug]/[dropId]/page.tsx",
  },

  /* ---------------------------- Customers ----------------------------- */
  {
    id: "customer-list",
    slug: "customer-list",
    title: "Your customer list",
    question: "Where can I see my customers?",
    summary: "Customers builds itself from your orders — who bought, how often, how much.",
    category: "customers",
    keywords: ["customers", "list", "buyers", "repeat", "who"],
    body: [
      p("The Customers page builds itself from your orders. Every buyer appears with how many orders they've placed, what they've spent, and when they last ordered. Repeat buyers are marked."),
      p("You don't add anyone by hand and there's nothing to import."),
    ],
    related: ["customers-vs-followers", "announcements", "message-a-customer"],
    routes: ["/dashboard/customers"],
    priority: 1,
    verifiedAgainst: "app/dashboard/customers/page.tsx",
  },
  {
    id: "customers-vs-followers",
    slug: "customers-vs-followers",
    title: "Customers and followers",
    question: "What's the difference between a customer and a follower?",
    summary: "A customer has bought from you. Following is something customers do on DropMeet — you can't message followers yet.",
    category: "customers",
    keywords: ["followers", "following", "customers", "difference", "subscribe"],
    body: [
      p("A customer is someone who has ordered from you. They appear on your Customers page and you can message them."),
      p("Following is separate: someone browsing DropMeet can follow a business to keep track of it. Following is not buying, and it is not permission to market to someone."),
      note("Right now DropQ does not give you a follower list or a way to message followers — announcements go to people who have ordered from you. If that changes, this article will say so."),
    ],
    related: ["customer-list", "announcements", "what-is-dropmeet"],
    priority: 2,
    verifiedAgainst: "prisma/schema.prisma CustomerVendor.followedAt, lib/messaging.ts resolveAudience (orders only)",
  },
  {
    id: "announcements",
    slug: "announcements",
    title: "Sending an announcement",
    question: "How do I message several customers at once?",
    summary: "From a drop, pick an audience of buyers and write once — each person gets it privately.",
    category: "customers",
    keywords: ["announcement", "broadcast", "message all", "everyone", "notify", "blast"],
    body: [
      p("On a drop's page, the customer communication panel lets you write one message and send it to a group: everyone in that drop, people with active orders, people whose orders are ready, or a few you pick."),
      p("Each person receives it in their own private conversation, never a group thread, so replies come back to you individually."),
      note("Audiences are built from orders. Only people who have ordered from you can be reached this way."),
    ],
    related: ["message-a-customer", "customers-vs-followers"],
    routes: ["/dashboard/messages", "/dashboard/customers"],
    priority: 3,
    verifiedAgainst: "lib/messaging.ts resolveAudience/sendBroadcast, components/broadcast-composer.tsx",
  },

  /* ----------------------------- DropMeet ----------------------------- */
  {
    id: "what-is-dropmeet",
    slug: "what-is-dropmeet",
    title: "What DropMeet is",
    question: "What is DropMeet?",
    summary: "A public map of local markets and places, and the vendors selling at them.",
    category: "dropmeet",
    keywords: ["dropmeet", "map", "markets", "discover", "local", "events"],
    body: [
      p("DropMeet is a public map of local markets, events and places, and the DropQ vendors appearing at them. Customers browse it to find who's selling nearby and preorder before they arrive."),
      p("DropMeet runs region by region, so it only shows anything where a region has been switched on."),
    ],
    related: ["appear-on-dropmeet", "discovery-settings"],
    requires: "dropmeet",
    routes: ["/dashboard/where-ill-be"],
    priority: 1,
    verifiedAgainst: "app/dropmeet/page.tsx, lib/dropmeet/query.ts dropMeetFeed",
  },
  {
    id: "appear-on-dropmeet",
    slug: "appear-on-dropmeet",
    title: "Appearing on DropMeet",
    question: "How do I show up on DropMeet?",
    summary: "Add where you'll be selling under Where I'll Be, and link a drop for preorders.",
    category: "dropmeet",
    keywords: ["where ill be", "appearance", "market", "stall", "booth", "attend"],
    body: [
      p("Under Where I'll Be, add the market, place or event you're selling at and when. You'll then show up on DropMeet for anyone browsing it."),
      p("You can attach one of your drops to an appearance, so customers can preorder before they arrive."),
    ],
    related: ["what-is-dropmeet", "discovery-settings"],
    requires: "dropmeet",
    routes: ["/dashboard/where-ill-be"],
    priority: 2,
    verifiedAgainst: "app/dashboard/where-ill-be/page.tsx, components/dropmeet/appearance-form.tsx",
  },
  {
    id: "discovery-settings",
    slug: "discovery-settings",
    title: "Being found on DropQ",
    question: "How do customers discover my store?",
    summary: "Discovery is off until you switch it on, and you control what's shown.",
    category: "dropmeet",
    keywords: ["discovery", "discoverable", "find me", "search", "public", "nearby"],
    body: [
      p("DropQ has a public Find Drops page for customers looking for vendors nearby. Your store does not appear there until you switch Discovery on."),
      p("Once on, you choose what's shown: your live drops, your appearances, and how precise your location is. Exact addresses are hidden by default — only the drop itself carries the address, and only for people who ordered."),
    ],
    related: ["what-is-dropmeet", "appear-on-dropmeet"],
    routes: ["/dashboard/discoverability"],
    priority: 3,
    verifiedAgainst: "app/dashboard/discoverability/page.tsx, prisma/schema.prisma Seller.isDiscoverable (default false)",
  },

  /* --------------------------- Walk-up sales -------------------------- */
  {
    id: "what-is-walkup",
    slug: "what-is-walkup",
    title: "Walk-up sales",
    question: "What is a walk-up sale?",
    summary: "Ringing up someone standing with you — they pay by card on their own phone.",
    category: "walkup",
    keywords: ["walk up", "walkup", "in person", "counter", "till", "market"],
    body: [
      p("A walk-up sale is for a customer standing in front of you. You add what they want, DropQ shows a QR code, they scan it and pay by card on their own phone."),
      p("It becomes a normal order once they've paid — same order list, same inventory, same payout."),
      note("DropQ doesn't handle cash. Anything you sell for cash is outside DropQ and won't appear in your orders or takings."),
    ],
    related: ["walkup-vs-online", "walkup-which-qr"],
    requires: "walkup",
    routes: ["/dashboard/drops"],
    priority: 1,
    verifiedAgainst: "lib/walkup.ts, app/dashboard/drops/[id]/sale/page.tsx",
  },
  {
    id: "walkup-vs-online",
    slug: "walkup-vs-online",
    title: "Walk-up vs a normal order",
    question: "How is a walk-up sale different from a normal order?",
    summary: "You build the cart instead of the customer, and payment happens right there.",
    category: "walkup",
    keywords: ["difference", "walk up", "online order", "compare"],
    body: [
      p("With an online order the customer finds your drop and builds their own cart. With a walk-up sale you build it while they wait, then hand them a QR to pay."),
      p("Everything after payment is identical: it's a normal paid order against the same drop and the same stock."),
      note("A walk-up cart is temporary. If it isn't paid it expires on its own, and nothing is reserved until payment goes through."),
    ],
    related: ["what-is-walkup", "walkup-which-qr"],
    requires: "walkup",
    priority: 2,
    verifiedAgainst: "lib/walkup.ts WALKUP_TTL_MINUTES, lib/actions/pay.ts",
  },
  {
    id: "walkup-which-qr",
    slug: "walkup-which-qr",
    title: "Which QR code to use in person",
    question: "Which QR code do I use for a walk-up sale?",
    summary: "The one on the sale screen — it's for that one customer's payment, not the drop.",
    category: "walkup",
    keywords: ["which qr", "walk up qr", "payment qr", "confuse", "two qr"],
    body: [
      p("There are two, and they do different things."),
      steps(
        "The drop QR opens your drop's public page. Print it, share it, put it on the table — anyone can scan it.",
        "The walk-up QR appears on the in-person sale screen and pays for that one cart. It is meant for one customer and expires.",
      ),
      p("If someone wants to browse and order themselves, point them at the drop QR. If you've just rung something up for them, show them the sale screen."),
    ],
    related: ["what-is-walkup", "drop-qr-code"],
    requires: "walkup",
    priority: 3,
    verifiedAgainst: "app/dashboard/drops/[id]/sale/page.tsx payUrl QR vs drop share QR",
  },

  /* -------------------------- Account & plan -------------------------- */
  {
    id: "plans-and-limits",
    slug: "plans-and-limits",
    title: "Plans and drop limits",
    question: "How many drops can I create?",
    summary: "Free includes three drops for the lifetime of the account. Paid plans are unlimited.",
    category: "account",
    keywords: ["plan", "limit", "free", "basic", "upgrade", "how many", "pricing"],
    body: [
      p("The Free plan includes three drops in total — for the lifetime of your account, not per month. Paid plans remove the limit."),
      p("Your Drops page shows how many you have left."),
    ],
    related: ["starter-drop-limit", "what-dropq-charges"],
    routes: ["/dashboard/billing", "/dashboard/drops"],
    priority: 1,
    verifiedAgainst: "lib/plans.ts STARTER_DROP_LIMIT/dropsRemaining",
  },
  {
    id: "starter-drop-limit",
    slug: "starter-drop-limit",
    title: "How the Free drop allowance is counted",
    question: "Does deleting a drop give me the slot back?",
    summary: "No. The count is of drops created, and deleting or relaunching never gives one back.",
    category: "account",
    keywords: ["lifetime", "allowance", "delete", "refund", "slot", "relaunch", "limit"],
    body: [
      p("The Free allowance counts drops you have created, and the count never goes down."),
      steps(
        "Deleting a drop does not give the slot back — including a test drop deleted straight away.",
        "Relaunch creates a NEW drop, so it spends another slot.",
        "Recreating a drop because you picked the wrong type spends another slot.",
      ),
      p("If you're trying DropQ out, it's worth using your first drop deliberately rather than as an experiment."),
    ],
    related: ["plans-and-limits", "relaunch-a-drop", "drop-types"],
    routes: ["/dashboard/drops", "/dashboard/billing"],
    priority: 2,
    verifiedAgainst: "lib/actions/dashboard.ts dropsCreated increment (createDropAction + duplicateDropAction), never decremented",
  },
  {
    id: "store-settings",
    slug: "store-settings",
    title: "Your store settings",
    question: "What can I change about my store?",
    summary: "Name, story, location, logo, colours and your timezone — all optional except the name.",
    category: "account",
    keywords: ["store", "settings", "profile", "logo", "colour", "color", "timezone", "brand"],
    body: [
      p("Store settings control what buyers see on your storefront: name, tagline, story, location, logo, header image, accent colour and social links."),
      p("Everything except the store name is optional, and none of it stops you selling."),
      note("The one setting with real mechanical weight is your timezone: it's what drop dates are interpreted and displayed in. Set it if you're not in the same zone as your customers."),
    ],
    related: ["what-you-need-to-start", "how-drop-dates-work", "pass-the-fee"],
    routes: ["/dashboard/store"],
    priority: 3,
    verifiedAgainst: "lib/actions/dashboard.ts updateStoreAction, components/store-settings-form.tsx",
  },
  {
    id: "verify-your-email",
    slug: "verify-your-email",
    title: "Verifying your email",
    question: "Do I have to verify my email?",
    summary: "It's worth doing for account security, but it doesn't stop you selling.",
    category: "account",
    keywords: ["verify", "email", "confirm", "verification", "required"],
    body: [
      p("DropQ emails you a verification link when you sign up. Verifying confirms the address is yours and is worth doing."),
      p("It does not gate anything. You can log in, build drops, publish and take orders with an unverified address — the notice on your dashboard is a reminder, not a block."),
    ],
    related: ["what-you-need-to-start"],
    priority: 4,
    verifiedAgainst: "app/dashboard/layout.tsx VerifyBanner, lib/activation.ts (email is not a milestone)",
  },
  {
    id: "restart-the-tour",
    slug: "restart-the-tour",
    title: "Taking the tour again",
    question: "Can I see the intro tour again?",
    summary: "Yes — it's in Help, any time, and it changes nothing about your account.",
    category: "account",
    keywords: ["tour", "restart", "again", "walkthrough", "intro", "onboarding"],
    body: [
      p("The six-step tour is in Help. Take it as often as you like."),
      p("Restarting it is purely a tour: it doesn't reset your checklist, your drops, or anything else about your account."),
    ],
    related: ["first-week"],
    priority: 5,
    verifiedAgainst: "lib/actions/guidance.ts startTourAction (writes only tour fields)",
  },

  /* -------------------------- Troubleshooting ------------------------- */
  {
    id: "why-cant-i-publish",
    slug: "why-cant-i-publish",
    title: "Why you can't publish",
    question: "Why can't I publish my drop?",
    summary: "Almost always Stripe: a drop can't go live until Stripe can take card payments for you.",
    category: "troubleshooting",
    keywords: ["cant publish", "can't publish", "publish", "blocked", "stripe", "draft", "won't"],
    body: [
      p("Publishing needs Stripe to be able to take charges for you. Until then DropQ shows the Stripe step in place of the Publish button and keeps your work as a draft."),
      steps(
        "If you haven't started Stripe, go to Payments and connect it.",
        "If you started but didn't finish, go back and complete Stripe's setup.",
        "If Stripe is reviewing you, wait and use Refresh status.",
        "If Stripe paused your account, fix what it's asking for in your Stripe dashboard.",
      ),
      note("Your drop is not lost. Everything you entered stays as a draft, and publishing works the moment Stripe is ready."),
    ],
    related: ["stripe-started-vs-ready", "connect-stripe", "stripe-stopped-working"],
    routes: ["/dashboard/drops", "/dashboard/payments"],
    priority: 1,
    verifiedAgainst: "lib/payments.ts resolveDropStatus, lib/activation.ts publishGate",
  },
  {
    id: "why-isnt-my-drop-visible",
    slug: "why-isnt-my-drop-visible",
    title: "Why your drop isn't visible",
    question: "Why isn't my drop showing up?",
    summary: "It's a draft, its order window hasn't opened, it has closed, or it was closed by you.",
    category: "troubleshooting",
    keywords: ["not visible", "cant see", "missing", "hidden", "not showing", "invisible"],
    body: [
      p("Open the drop — its status says which of these it is."),
      steps(
        "Draft — it hasn't been published, so it isn't public yet.",
        "Scheduled — published, but the order window hasn't opened.",
        "The order window has already closed, which happens automatically at the close time.",
        "You closed the drop.",
      ),
      p("A published drop with an open window is visible on your storefront and at its own link."),
    ],
    related: ["why-cant-customers-order", "how-drop-dates-work", "publish-a-drop"],
    routes: ["/dashboard/drops"],
    priority: 2,
    verifiedAgainst: "lib/drop-status.ts computeDropPhase/isOrderingOpen",
  },
  {
    id: "why-cant-customers-order",
    slug: "why-cant-customers-order",
    title: "Why customers can't order",
    question: "Why can't customers order from my drop?",
    summary: "Check the drop is live, the order window is open, and stock is left.",
    category: "troubleshooting",
    keywords: ["cant order", "customers", "checkout", "not working", "order failed"],
    body: [
      steps(
        "Is the drop published rather than a draft?",
        "Is the order window open right now? Ordering locks at the close time.",
        "Is anything left? A drop where every item is sold out has nothing to buy.",
        "Can Stripe still take payments for you? If it has been paused, your storefront stops taking orders.",
      ),
      p("Opening your own drop link on your phone is the quickest way to see exactly what customers see."),
    ],
    related: ["why-isnt-my-drop-visible", "stripe-stopped-working", "sold-out"],
    routes: ["/dashboard/drops"],
    priority: 3,
    verifiedAgainst: "lib/drop-status.ts isOrderingOpen, lib/actions/order.ts placeOrderAction",
  },
  {
    id: "customer-didnt-get-email",
    slug: "customer-didnt-get-email",
    title: "If a customer didn't get their confirmation",
    question: "A customer says they didn't get a confirmation email. What now?",
    summary: "Check the order exists and is paid, then message them directly from the order.",
    category: "troubleshooting",
    keywords: ["email", "confirmation", "not received", "receipt", "missing email"],
    body: [
      p("First check the order is in your list and marked paid — if it isn't there, the payment didn't complete and they weren't charged."),
      p("If the order is there, the mail may have been filtered. Use the Message button on the order to reach them in DropQ, which doesn't depend on email getting through."),
    ],
    related: ["is-an-order-paid", "message-a-customer"],
    routes: ["/dashboard/orders"],
    priority: 4,
    verifiedAgainst: "lib/checkout.ts finalizePaidOrder, lib/messaging.ts",
  },
];
